# Generated by Django 2.2.24 on 2022-04-26 08:33

import phonenumbers
from django.db import migrations


def fill_normalized_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone) \
                and phonenumbers.is_possible_number(phone):
            flat.owner_pure_phonenamber = phone
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phonenamber'),
    ]

    operations = [
        migrations.RunPython(fill_normalized_phonenumbers),
    ]
