# Generated by Django 2.2.24 on 2022-04-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220426_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_pure_phonenamber',
            new_name='owner_pure_phonenumber',
        ),
    ]
