# Generated by Django 2.2.24 on 2022-05-05 09:04

from django.db import migrations


def fill_owners_table(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner, phone=flat.owners_phonenumber, defaults={
                'pure_phone': flat.owner_pure_phonenumber,
            })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners_table)
    ]
