# Generated by Django 2.2.24 on 2022-05-05 11:24

from django.db import migrations


def bind_entities(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.update_or_create(
            name=flat.owner, phone=flat.owners_phonenumber,
            defaults={
                'pure_phone': flat.owner_pure_phonenumber,
            })
        owner.flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220505_1204'),
    ]

    operations = [
        migrations.RunPython(bind_entities)
    ]
