# Generated by Django 2.2.24 on 2022-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220505_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, 'Неизвестно')], db_index=True, null=True, verbose_name='Новостройка'),
        ),
    ]
